import os
import shutil
import json
import re

base_dir = "/Users/abdullah/Pytorch"
temp_dir = os.path.join(base_dir, "temp")
template_dir = os.path.join(base_dir, "TEMPLATE")
target_dir = os.path.join(base_dir, "multi-gpu-transformer")

# Copy template
if not os.path.exists(target_dir):
    shutil.copytree(template_dir, target_dir)

# 1. Update README.md
readme_path = os.path.join(target_dir, "README.md")
with open(readme_path, "r") as f:
    readme = f.read()

readme = readme.replace('[Descriptive Title — e.g., "Latent Space Alignment via Relative Representations"]', "Distributed PyTorch & Transformer Implementations")
readme = readme.replace('[Full paper title](link-to-arxiv-or-paper)', '[Attention Is All You Need](https://arxiv.org/abs/1706.03762) & [YouTube Tutorial](https://www.youtube.com/watch?v=-LAtx9Q6DA8&list=PL_lsbAsL_o2CSuhUhJIiW0IkdT5C2wGWj&index=3)')
readme = readme.replace('Author 1, Author 2, ...', 'Vaswani et al.')
readme = readme.replace('20XX', '2017')

why_this_paper = """I wanted to try distributed PyTorch and in general I am pursuing my interest in distributed computing. The YouTube video was a great resource as it demonstrated training on a rented 4x 3060 setup."""

key_idea = """The key idea here is implementing Transformers from scratch (mostly), and testing the training process both on a single GPU and distributed across multiple GPUs (DDP). This also touches upon understanding theoretical bounds like compute-bound vs communication-bound, rooflines, and arithmetic intensity when communicating between chips."""

what_implemented = """- Implemented most of the core Transformer components (`Linear`, `Embedding`, `MLP`, `LayerNorm`, `MultiHeadAttention`, `GPTTransformer`) from scratch.
- Skipped data loading and positional encoding (AI generated).
- Used the YouTube tutorial for the distributed compute/DDP logic."""

results_takeaways = """Results from training on 4× RTX 3060s vs Single GPU baseline:

| | Single GPU | 4× GPU (DDP) |
|---|---|---|
| **Wall time** | 18.21s | **7.48s** |
| **Batches processed** | 1,218 | 305 × 4 = 1,220 ✅ |
| **Speedup** | 1× | **2.43×** |

The 2.43× speedup is expected because of DDP overhead (NCCL AllReduce), a tiny dataset, and small batch sizes which lower the compute-to-communication ratio."""

readme = re.sub(r'## Why This Paper\?\n\n_How did you come across it\?.*?journey._', f'## Why This Paper?\n\n{why_this_paper}', readme, flags=re.DOTALL)
readme = re.sub(r'## Key Idea\n\n_Plain-English.*?aha moment"\?_', f'## Key Idea\n\n{key_idea}', readme, flags=re.DOTALL)
readme = re.sub(r'## What I Implemented\n\n-.*?production pipeline."', f'## What I Implemented\n\n{what_implemented}', readme, flags=re.DOTALL)
readme = re.sub(r'## Results & Takeaways\n\n_What did you observe\?.*?insights\?_', f'## Results & Takeaways\n\n{results_takeaways}', readme, flags=re.DOTALL)

# Add scripts to Files table
files_table_additions = """| `train_single.py` | Training script for a single GPU |
| `train_ddp.py` | Distributed training script using DDP |"""
readme = readme.replace('| `assets/` | Saved figures, embeddings, etc. |', f'| `assets/` | Saved figures, embeddings, etc. |\n{files_table_additions}')

with open(readme_path, "w") as f:
    f.write(readme)

# 2. Modify Notebook
nb_path = os.path.join(temp_dir, "MultiGPUTransformer.ipynb")
if os.path.exists(nb_path):
    with open(nb_path, "r") as f:
        nb = json.load(f)

    new_cells = []
    new_cells.append({"cell_type": "markdown", "metadata": {}, "source": ["> 🤖 **AI-Assisted** — Imports & Data Loading"]})

    for i, cell in enumerate(nb["cells"]):
        if i == 4:
            new_cells.append({"cell_type": "markdown", "metadata": {}, "source": ["> ✍️ **My Work** — Core model components (Linear, Embedding, MLP) implemented from scratch"]})
        if i == 7:
            new_cells.append({"cell_type": "markdown", "metadata": {}, "source": ["> 🤖 **AI-Assisted** — Positional Encoding generated by AI"]})
            continue # skip the original '#pos enc is ai generated'
        if i == 9:
            new_cells.append({"cell_type": "markdown", "metadata": {}, "source": ["> ✍️ **My Work** — LayerNorm, MultiHeadAttention, and overall Transformer assembly"]})
        if i == 15:
            new_cells.append({"cell_type": "markdown", "metadata": {}, "source": ["> 🤖 **AI-Assisted** — Distributed computing logic adapted from YouTube tutorial"]})
            
        # Clean up the crash output from DDP in notebook
        if cell.get("execution_count") == 54:
            cell["outputs"] = []

        new_cells.append(cell)

    nb["cells"] = new_cells

    target_nb_path = os.path.join(target_dir, "experiment.ipynb")
    with open(target_nb_path, "w") as f:
        json.dump(nb, f, indent=1)

# 3. Copy Python Scripts
if os.path.exists(os.path.join(temp_dir, "train_ddp.py")):
    shutil.copy(os.path.join(temp_dir, "train_ddp.py"), os.path.join(target_dir, "train_ddp.py"))
if os.path.exists(os.path.join(temp_dir, "train_single.py")):
    shutil.copy(os.path.join(temp_dir, "train_single.py"), os.path.join(target_dir, "train_single.py"))

# Clean up template notebook if it copied
template_nb = os.path.join(target_dir, "notebook_template.ipynb")
if os.path.exists(template_nb):
    os.remove(template_nb)
    
print("Successfully processed new paper!")
